version: '3'
services:
  zigbee2mqtt-first:
    image: koenkk/zigbee2mqtt:latest
    volumes:
      - /[first local path for config]:/app/data
#    devices:
#      - /dev/ttyACM0:/dev/ttyACM0
    restart: always
    network_mode: host
    environment:
      - TZ=[your timezone]

  zigbee2mqtt-second:
    image: koenkk/zigbee2mqtt:latest
    volumes:
      - /[second local path for config]:/app/data
#    devices:
#      - /dev/null:/dev/ttyACM0
    restart: always
    network_mode: host
    environment:
      - TZ=[your timezone]
